---
apiVersion: v1
kind: Service
metadata:
  name: piveau-consus-importing-oaipmh
  labels:
    app: piveau-consus-importing-oaipmh
spec:
  ports:
    - name: http
      port: 8080
      targetPort: default
      protocol: TCP
  selector:
    app: piveau-consus-importing-oaipmh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: piveau-consus-importing-oaipmh
  name: piveau-consus-importing-oaipmh
spec:
  selector:
    matchLabels:
      app: piveau-consus-importing-oaipmh
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: piveau-consus-importing-oaipmh
    spec:
      containers:
        - name: piveau-consus-importing-oaipmh
          image: dockerhub.fokus.fraunhofer.de:5000/piveau/consus/piveau-consus-importing-oaipmh:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: default
          startupProbe:
            httpGet:
              path: /health
              port: default
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: default
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: JAVA_OPTS
              value: -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError
